In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
filename = 'C:/Users/Asus/Documents/Data Sci team/Datathon.csv'

# Read data from file 'filename.csv' 
# (in the same directory that your python process is based)
# Control delimiters, rows, column names with read_csv (see later) 
data = pd.read_csv("C:/Users/Asus/Documents/Data Sci team/Datathon.csv") 
# Preview the first 5 lines of the loaded data 
data

,Timestamp,Email Address,Team Name,Number of the team members,Name,Surname,Gender,year of study,"Major, Year of Study","Email address (be attentive, all further information will be sent to this email address)",...,"Major, Year of Study.1",Months/Years of Experience in Data Science.1,2nd participant's Name,2nd participant's Surname,2nd participant Year of Study,"2nd participant's Major, Year of Study",2nd participant's Gender,2nd participant's Months/Years of Experience in Data Science,"Email address (be attentive, all further information will be sent to this email address) .1",Phone Number.1
0,9/22/2020 20:58:46,kaisar.dauletbek@nu.edu.kz,KD,1,Kaisar,Dauletbek,Male,2,Language Linguistics Literature,kaisar.dauletbek@nu.edu.kz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9/22/2020 21:04:13,serik.zhilibayev@nu.edu.kz,Единал,1,Serik,Zhilibayev,Male,2,Data Science M,serik.zhilibayev@nu.edu.kz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9/22/2020 21:09:30,yermukhamet.medetov@nu.edu.kz,YT,2,NaN,NaN,NaN,NaN,NaN,NaN,...,Applied math MSc,6 - 12 months,Temirlan,Ashimov,2,Applied math M,Other,6 - 12 months,yermukhamet.medetov@nu.edu.kz,8.701759e+10
3,9/22/2020 21:20:49,kuat.madeniyet@nu.edu.kz,DLWP,1,Kuat,Madeniyet,Male,Alumni 2020,Electrical and Computer Engineering,kuat.madeniyet@nu.edu.kz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9/22/2020 21:41:58,beket.myrzanov@nu.edu.kz,Beket Myrzanov,1,Beket,Myrzanov,Male,2,Computer Science,beket0101@gmail.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,10/2/2020 17:47:44,agerbolt@nu.edu.kz,Melted Chrome,1,Angelina,Gerbolt,Female,Alumni 2020,Computer Science M,agerbolt@nu.edu.kz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,10/2/2020 19:44:20,mukhit.yelemes@nu.edu.kz,MUHA,1,Mukhit,Yelemes,Male,1,Data Science M,mukhit.yelemes@nu.edu.kz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,10/2/2020 20:08:25,timur.okhassov@nu.edu.kz,Timur,1,Timur,Okhassov,Male,4,Electrical and Computer Engineering,timur.okhassov@nu.edu.kz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,10/2/2020 21:25:30,islambek.temirbek@nu.edu.kz,ITemirbek,1,Islambek,Temirbek,Male,Alumni 2020,NaN,islambek.temirbek@nu.edu.kz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,10/2/2020 21:32:12,anuar.idrissov@nu.edu.kz,Idrissov,1,Anuar,Idrissov,Male,1,Physics,anuar.idrissov@gmail.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data['year of study']

0               2
1               2
2             NaN
3     Alumni 2020
4               2
         ...
77    Alumni 2020
78              1
79              4
80    Alumni 2020
81              1
Name: year of study, Length: 82, dtype: object

In [5]:
majorname1=data['Major, Year of Study']

In [6]:
yearofstudy2=data['2nd participant Year of Study']

In [7]:
data.columns = data.columns.str.replace("'"," ")

In [8]:
data

,Timestamp,Email Address,Team Name,Number of the team members,Name,Surname,Gender,year of study,"Major, Year of Study","Email address (be attentive, all further information will be sent to this email address)",...,"Major, Year of Study.1",Months/Years of Experience in Data Science.1,2nd participant s Name,2nd participant s Surname,2nd participant Year of Study,"2nd participant s Major, Year of Study",2nd participant s Gender,2nd participant s Months/Years of Experience in Data Science,"Email address (be attentive, all further information will be sent to this email address) .1",Phone Number.1
0,9/22/2020 20:58:46,kaisar.dauletbek@nu.edu.kz,KD,1,Kaisar,Dauletbek,Male,2,Language Linguistics Literature,kaisar.dauletbek@nu.edu.kz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9/22/2020 21:04:13,serik.zhilibayev@nu.edu.kz,Единал,1,Serik,Zhilibayev,Male,2,Data Science M,serik.zhilibayev@nu.edu.kz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9/22/2020 21:09:30,yermukhamet.medetov@nu.edu.kz,YT,2,NaN,NaN,NaN,NaN,NaN,NaN,...,Applied math MSc,6 - 12 months,Temirlan,Ashimov,2,Applied math M,Other,6 - 12 months,yermukhamet.medetov@nu.edu.kz,8.701759e+10
3,9/22/2020 21:20:49,kuat.madeniyet@nu.edu.kz,DLWP,1,Kuat,Madeniyet,Male,Alumni 2020,Electrical and Computer Engineering,kuat.madeniyet@nu.edu.kz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9/22/2020 21:41:58,beket.myrzanov@nu.edu.kz,Beket Myrzanov,1,Beket,Myrzanov,Male,2,Computer Science,beket0101@gmail.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,10/2/2020 17:47:44,agerbolt@nu.edu.kz,Melted Chrome,1,Angelina,Gerbolt,Female,Alumni 2020,Computer Science M,agerbolt@nu.edu.kz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,10/2/2020 19:44:20,mukhit.yelemes@nu.edu.kz,MUHA,1,Mukhit,Yelemes,Male,1,Data Science M,mukhit.yelemes@nu.edu.kz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,10/2/2020 20:08:25,timur.okhassov@nu.edu.kz,Timur,1,Timur,Okhassov,Male,4,Electrical and Computer Engineering,timur.okhassov@nu.edu.kz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,10/2/2020 21:25:30,islambek.temirbek@nu.edu.kz,ITemirbek,1,Islambek,Temirbek,Male,Alumni 2020,NaN,islambek.temirbek@nu.edu.kz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,10/2/2020 21:32:12,anuar.idrissov@nu.edu.kz,Idrissov,1,Anuar,Idrissov,Male,1,Physics,anuar.idrissov@gmail.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
majorname2=data['2nd participant s Major, Year of Study']

In [10]:
majorname2=majorname2.dropna()

In [11]:
majorname1=majorname1.dropna()

In [12]:
len(majorname1)

35

In [13]:
len(majorname2)

46

In [14]:
for col in data.columns:
    print(col)

Timestamp
Email Address
Team Name
Number of the team members
Name
Surname
Gender
year of study
Major, Year of Study
Email address (be attentive, all further information will be sent to this email address)
Phone Number
Months/Years of Experience in Data Science
 Name
Surname.1
Gender.1
year of study.1
Major, Year of Study.1
Months/Years of Experience in Data Science.1
2nd participant s Name
2nd participant s Surname
2nd participant Year of Study
2nd participant s Major, Year of Study
2nd participant s Gender
2nd participant s Months/Years of Experience in Data Science
Email address (be attentive, all further information will be sent to this email address) .1
Phone Number.1

In [31]:
data['Major, Year of Study.1'].dropna()

2                          Applied math MSc
5                                  Robotics
9                                      Math
10                                    SEDS
11                                     Math
14                                     Math
15                                Economics
16                 Engineering Management M
17                                     Math
18                     Chemical Engineering
19                         Computer Science
20                         Computer Science
21                                 Robotics
22                         Computer Science
23                         Computer Science
24                         Computer Science
25                      Computers Science M
27                         ECE, 1 year Grad
28                           Data Science M
29                           Data Science M
30                           Data Science M
31                           Data Science M
32                                Physics M
33                           Data science M
35                         Computer Science
37                         Computer Science
40                         Computer Science
41                                Economics
42                                Economics
44                          Public Health M
46                                     Math
49    Electrical and Computer Engineering M
50                                   CPS, 1
51                                 Robotics
52                                 Robotics
53                   Mechanical Engineering
57                                     Math
58                                Economics
59                                Economics
60                         Computer science
62                         Computer science
63                         Computer science
64                         Computer science
74                                   NUFYP
75                         Computer Science
76                        Civil Engineering
Name: Major, Year of Study.1, dtype: object

In [29]:
data['Major, Year of Study.1'].dropna()

2                          Applied math MSc
5                                  Robotics
9                                      Math
10                                    SEDS
11                                     Math
14                                     Math
15                                Economics
16                 Engineering Management M
17                                     Math
18                     Chemical Engineering
19                         Computer Science
20                         Computer Science
21                                 Robotics
22                         Computer Science
23                         Computer Science
24                         Computer Science
25                      Computers Science M
27                         ECE, 1 year Grad
28                           Data Science M
29                           Data Science M
30                           Data Science M
31                           Data Science M
32                                Physics M
33                           Data science M
35                         Computer Science
37                         Computer Science
40                         Computer Science
41                                Economics
42                                Economics
44                          Public Health M
46                                     Math
49    Electrical and Computer Engineering M
50                                   CPS, 1
51                                 Robotics
52                                 Robotics
53                   Mechanical Engineering
57                                     Math
58                                Economics
59                                Economics
60                         Computer science
62                         Computer science
63                         Computer science
64                         Computer science
74                                   NUFYP
75                         Computer Science
76                        Civil Engineering
Name: Major, Year of Study.1, dtype: object

In [52]:
len(data['2nd participant s Major, Year of Study'].dropna())

46

In [51]:
len(data['2nd participant Year of Study'].dropna())

37

In [35]:
len(data['Email address (be attentive, all further information will be sent to this email address) '].dropna())

36

In [34]:
len(data['Email address (be attentive, all further information will be sent to this email address) .1'].dropna())

46

In [41]:
email= pd.read_csv("C:/Users/Asus/Documents/NU SALTA/agri_dataset_2020/email.csv", delimiter='\t')

In [42]:
email

                           email
0     kaisar.dauletbek@nu.edu.kz
1     serik.zhilibayev@nu.edu.kz
2       kuat.madeniyet@nu.edu.kz
3            beket0101@gmail.com
4      mohammad.bayat@nu.edu.kz
..                           ...
77   shynggys.saparbek@nu.edu.kz
78       amina.shaikym@nu.edu.kz
79         sherkhan.NU@yandex.ru
80  bakdauren.narbayev@nu.edu.kz
81            kasymmkk@gmail.com

[82 rows x 1 columns]

In [43]:
uniqueValues = email['email'].unique()

In [45]:
len(uniqueValues)

79

In [46]:
uniqueValues

array(['kaisar.dauletbek@nu.edu.kz', 'serik.zhilibayev@nu.edu.kz',
       'kuat.madeniyet@nu.edu.kz', 'beket0101@gmail.com',
       'mohammad.bayat@nu.edu.kz ', 'nazym.shakirkhozha@nu.edu.kz',
       'ulugbek.alibekov@nu.edu.kz', 'farkhad.kuanyshkereyev@nu.edu.kz',
       'alfarabi.nagashbayev@nu.edu.kz', 'makar.lezhnikov@nu.edu.kz',
       'aidynbek.tussipzhan@nu.edu.kz', 'arman.tarpanov@nu.edu.kz',
       'abilkair.bolatbayev@nu.edu.kz', 'serik.almakhan@nu.edu.kz',
       'olzhas.sutemgenov@nu.edu.kz', 'ulanbek.kurmaniyazov@nu.edu.kz',
       'aidynkadyr@gmail.com', 'zhanibek.darimbekov@nu.edu.kz',
       'meiirlan.suiirkhanov@nu.edu.kz', 'nurbolat.bazarbek@nu.edu.kz',
       'alisher.amantay@nu.edu.kz', 'gulnur.maulenova@nu.edu.kz',
       'alibi.kaiyr@nu.edu.kz', 'vladislav.yarovenko@nu.edu.kz',
       'timur.rakhimzhan@gmail.com', 'milka3341@gmail.com',
       'rustem.turtayev@nu.edu.kz', 'damilya.saduakhas@nu.edu.kz',
       'temirlan.auyespek@nu.edu.kz', 'babkenovk@gmail.com',
       'agerbolt@nu.edu.kz', 'mukhit.yelemes@nu.edu.kz',
       'timur.okhassov@nu.edu.kz', 'islambek.temirbek@nu.edu.kz',
       'anuar.idrissov@gmail.com', 'yermukhamet.medetov@nu.edu.kz',
       'bauyrzhan.zhakanov@nu.edu.kz', 'kamila.kameshova@nu.edu.kz',
       'magzhan.zhuzimkhan@nu.edu.kz ', 'dina.shilibekova@nu.edu.kz',
       'tamila.tazhibayeva@nu.edu.kz', 'amina.yensegenova@nu.edu.kz',
       'nurtay.beltenov@nu.edu.kz', 'sana.ramazanova@nu.edu.kz',
       'olzhas.santay@nu.edu.kz', 'Kenessov.daryn@nu.edu.kz',
       'altynbek.aidarbekov@nu.edu.kz', 'ruslan.shaimerdenuly@nu.edu.kz',
       'mr.nuradil@gmail.com', 'rasul.yermagambet@nu.edu.kz ',
       'albina.li@nu.edu.kz', 'aldiyar.dabarov@nu.edu.kz',
       'yerlan.amanzholov@nu.edu.kz', 'assem.kussainova@nu.edu.kz',
       'aigerim.janaliyeva@nu.edu.kz', 'adilkhan.sarsen@nu.edu.kz',
       'gauhar.omarova@nu.edu.kz', 'maxim.mametkulov@nu.edu.kz',
       'islam.shintemirov@nu.edu.kz', 'rustam.zhumagambetov@nu.edu.kz',
       'sandi.seiitzhan@nu.edu.kz and ainat.abylgaziyeva@nu.edu.kz',
       'amina.kurmantayeva@nu.edu.kz', 'arnur.gusmanov@nu.edu.kz',
       'saniya.abushakimova@nu.edu.kz',
       'kuanysh.yessenzhanov@nu.edu.kz, anuar.syzdykov@nu.edu.kz',
       'berdalak@gmail.com', 'maksat.bekkuliyev@nu.edu.kz',
       'daryn.uteuliyev@nu.edu.kz', 'darkhan.shyrynbay@nu.edu.kz',
       'moldir.berkaliyeva@nu.edu.kz', 'dariya.talasbayeva@nu.edu.kz',
       'ibrahim.uali@nu.edu.kz ', 'korlan.zhumabekova@nu.edu.kz',
       'marat.serikbaev@nu.edu.kz, maracrasavap@gmail.com',
       'shynggys.saparbek@nu.edu.kz', 'amina.shaikym@nu.edu.kz',
       'sherkhan.NU@yandex.ru', 'bakdauren.narbayev@nu.edu.kz',
       'kasymmkk@gmail.com'], dtype=object)

In [47]:
uniqueValues = email.nunique()

In [48]:
uniqueValues

email    79
dtype: int64

In [49]:
frequency = email['email'].value_counts()

In [50]:
frequency

nazym.shakirkhozha@nu.edu.kz        2
farkhad.kuanyshkereyev@nu.edu.kz    2
assem.kussainova@nu.edu.kz          2
kaisar.dauletbek@nu.edu.kz          1
vladislav.yarovenko@nu.edu.kz       1
                                   ..
ruslan.shaimerdenuly@nu.edu.kz      1
yerlan.amanzholov@nu.edu.kz         1
albina.li@nu.edu.kz                 1
beket0101@gmail.com                 1
rustem.turtayev@nu.edu.kz           1
Name: email, Length: 79, dtype: int64

In [53]:
major= pd.read_csv("C:/Users/Asus/Documents/NU SALTA/agri_dataset_2020/major.csv", delimiter='\t')

In [54]:
major

                         Applied math MSc
0                                Robotics
1                                    Math
2                                   SEDS
3                                    Math
4                                    Math
..                                    ...
86                       Computer Science
87                       Computer Science
88                       Computer Science
89                       Computer Science
90  Electrical and Electronic Engineering

[91 rows x 1 columns]

In [85]:
datathon= pd.read_csv('C:/Users/Asus/Documents/DataSci/datathon1.csv', header=None)

In [86]:
datathon

                                                    0
0   email;major;Degree;YEAR OF STUDY;number of tea...
1   kaisar.dauletbek@nu.edu.kz;Language Linguistic...
2      serik.zhilibayev@nu.edu.kz;Data Science ;M;4;1
3   kuat.madeniyet@nu.edu.kz;Electrical and Comput...
4          beket0101@gmail.com;Computer Science;B;1;1
..                                                ...
78  bakdauren.narbayev@nu.edu.kz;Computer Science;...
79  kasymmkk@gmail.com;Electrical and Electronic E...
80                   ainat.abylgaziyeva@nu.edu.kz;;;;
81                       anuar.syzdykov@nu.edu.kz;;;;
82                         maracrasavap@gmail.com;;;;

[83 rows x 1 columns]

In [26]:
data['2nd participant Year of Study'].dropna()